### ISSUE TITLE
[!] Error running Sub-Finder: Command failed: [solution suggestion]

### ISSUE THREAD

**Issue by ghost** [pikpikcu/nodesub#7]
Hello, when using node sub, an error related to subfinder appeared in the middle of the scan. After a little look, I saw that the "-all" part at this point
`
        const commands = [
            'subfinder -all -d "${domain}" -rl 100 -recursive',
            'subfinder -all -d "${domain}" -rl 1000 -active',
        ];
`

 in the runSubfinder function, which started on line 659 in nodesub.js, was not found in the subfinder, I don't know if it's just me, but I didn't know if it was the "`-all`" option in this section. I solved the leverage, I wanted to report in case others may have good improvements.
 
 My system: [kali linux 2023.1]

I deliberately replaced the " ` " statements with " ' " in the command section as it caused problems in the report text.

**Comment by pikpikcu** [comment]
Thank you, this problem has been resolved.
